#!/usr/bin/env ruby
# generate DOT file from the relation data generated by `generate_relation_data`

BLOGS = {}

ARGF.each_line do |line|
  if line =~ /^(.*) (.*) (.*)$/
    blog1 = $1.tr('-','_')
    blog2 = $2.tr('-','_')
    weight = $3

    blog1 = "_"+blog1 if blog1 =~ /^[0-9]/
    blog2 = "_"+blog2 if blog2 =~ /^[0-9]/

    BLOGS[blog1] ||= {}
    BLOGS[blog1][blog2] = weight.to_i
  end
end



puts "digraph G {"
puts <<END
  graph [ overlap=false; outputorder=edgesfirst; sep="+40,40"; ];
  edge [ color="#00000066" ];
  node [ fillcolor=white; style=filled, fontname="Helvetica Neue LT Pro", shape=box ];
END

BLOGS.each_pair do |blog1, values|
  max = values.map{|k,v| v}.max
  values.each do |blog2, weight|
    if weight!=max && BLOGS.dig(blog2,blog1)
      puts "  #{blog1} -> #{blog2} [weight=#{weight}];"
    end
  end
end

BLOGS.each_pair do |blog1, values|
  max = values.map{|k,v| v}.max
  values.each do |blog2, weight|
    if weight == max && BLOGS.dig(blog2,blog1)
      puts "  #{blog1} -> #{blog2} [weight=#{weight}; penwidth = 1.5; color=\"#660000FF\"];"
    end
  end
end
puts "}"
